/*
** Copyright (C) 2014 independIT Integrative Technologies GmbH
*/

CREATE INDEX SME2LOAD_IDX ON SME2LOAD (ID) WITH STRUCTURE = BTREE;
\g
CREATE INDEX SME_IDX ON SUBMITTED_ENTITY (MASTER_ID, ID, STATE, FINAL_TS) WITH STRUCTURE = BTREE;
\g
CREATE INDEX KILL_JOB_IDX ON KILL_JOB (SME_ID) WITH STRUCTURE = BTREE;
\g
CREATE INDEX AUDIT_TRAIL_IDX ON AUDIT_TRAIL (OBJECT_ID) WITH STRUCTURE = BTREE;
\g
CREATE INDEX ENTITY_VARIABLE_IDX ON ENTITY_VARIABLE (SME_ID) WITH STRUCTURE = BTREE;
\g
CREATE INDEX DEPENDENCY_INSTANCE_IDX ON DEPENDENCY_INSTANCE (DEPENDENT_ID) WITH STRUCTURE = BTREE;
\g
CREATE INDEX HIERARCHY_INSTANCE_IDX ON HIERARCHY_INSTANCE (CHILD_ID) WITH STRUCTURE = BTREE;
\g

